name: irama
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  card_swiper: ^2.0.4
  carousel_slider: ^4.2.1
  flutter_launcher_icons: ^0.12.0
  introduction_screen: ^3.1.6
  dio: ^5.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: 'launcher_icon'
  ios: true
  image_path: 'assets/icon.png'

flutter:
  uses-material-design: true
  assets:
    - assets/
    - api/
